### ISSUE TITLE
oldest backup config

### ISSUE THREAD

**Issue by phit** [elytra/BTFU#10]
I would like to trim down the amount of history saved to say the last 7 days, I have no benefit of having a full history and would rather have higher frequency in recent time. Right now I have a script that wipes backups when they are older than 7 days to not fill up the amount with ancient stuff.
This especially becomes important when the server has been online for half a year or longer and more and more backup "slots" are taken up by ancient backups I will never need.

Should a be a pretty simple feature to add, but I don't feel comfortable enough with Scala to make a PR.

**Comment by alexbobp** [comment]
Hey, you got it.  Sorry I just noticed this, I've been working my ass off on the lingering loot 4.0 update, but yeah this seems pretty reasonable to do.

Don't be afraid to take a stab at scala!  It's a fun language and I can clean up a PR if needed.  But yeah I can get this done soon.

**Comment by phit** [comment]
No worries! I might if I get bored, otherwise take your time. My current script solution works fine for now ;)

**Comment by alexbobp** [comment]
Yeah, it's easy to script.  Now that I think of it, would you find general script hooks useful?  Like config options for pre_backup and pre_trim?  (pre_trim would be the right place to hook in an external script to do this, if we weren't going to add it to the tool itself which we might as well)

**Comment by phit** [comment]
could be nice if it isn't too much effort, but outside of what I'm doing now I personally won't have any use for it, but others might!

**Comment by alexbobp** [comment]
Fair, I'd wait to hear from someone who has a use for that.  I am already doing some overengineering on my other mod that nobody asked for!

**Comment by alexbobp** [comment]
The feature is working well.  It is just a simple config option for maximum backup age in days.  Note that it will actually always maintain exactly one backup older than the cutoff.  I am doing a version bump and uploading to curseforge.

**Comment by alexbobp** [comment]
also https://ci.elytradev.com/job/elytra/job/BTFU/job/master/13/
