### ISSUE TITLE
Player Presence

### ISSUE THREAD

**Issue by BinaryAura** [elytra/BTFU#14]
Could there by a setting in the config file to prevent backups when no one is one the server? Or would the benefit this would bring invalidated by rsync and logarthmic pruning?

**Comment by alexbobp** [comment]
Sorry I forgot to comment sooner!  Yes, this is a very reasonable ask.  The logarithmic pruning helps, but this could definitely allow for keeping more of the backups you care about on a server that spends most of its time empty.

My friend Nikky is working on the change in this PR: https://github.com/elytra/BTFU/pull/15

**Comment by alexbobp** [comment]
It's in the code now.  As implemented, it will always take the next scheduled backup after the last player logs off, but then skip any backups during which there was no player activity since the last one.  It will always take one backup after a server start.

**Comment by NikkyAI** [comment]
feel free to test the feature from #15 https://ci.elytradev.com/job/elytra/job/BTFU/job/multi-version/

**Comment by NikkyAI** [comment]
can this be closed then ?

**Comment by BinaryAura** [comment]
Yeah, this is great.
